Database:
  Host: localhost
  Port: 5432
  Name: miniplayertitle
  User: miniplayertitle
  Pass: miniplayertitle

Prefix: "["
Suffix: "]"

CustomCost:
  Enabled: true
  Cost: 1000
  MaxLength: 8

DefaultCoin: 0

Debug: false