Database:
  Type: sqlite # pgsql, sqlite
  Host: localhost
  Port: 5432
  Name: miniplayertitle
  User: miniplayertitle
  Pass: miniplayertitle

Prefix: "["
Suffix: "]"

CustomCost:
  Enabled: true
  Cost: 1000
  MaxLength: 8

DefaultCoin: 0

ExternalEco: false  # 使用外部经济插件 需要Vault支持

CheckUpdate: true

Debug: false