name: MiniPlayerTitle
version: '${project.version}'
main: cn.lunadeer.miniplayertitle.MiniPlayerTitle
api-version: '1.20'
description: 称号插件。
website: https://lunadeer.cn
folia-supported: true
softdepend: [PlaceholderAPI, Vault]
commands:
  MiniPlayerTitle:
    description: 称号插件命令
    usage: /mplt <cmd>
    aliases: [mplt]
