name: NewbTitle
version: '${project.version}'
main: cn.lunadeer.newbtitle.NewbTitle
api-version: '1.20'
description: 称号插件。
website: https://lunadeer.cn
folia-supported: true
commands:
  NewbTitle:
    description: 称号插件命令
    usage: /nt <cmd>
    aliases: [nt]
